Traverse style chain instead of taking the first style name directly
Vitaliy-1/docxToJats pull request #10
Opened 2020-05-05 12:05 UTC by sjamaan

Users can define their own styles, which may inherit from built-in
styles.  This results in a style chain (the built-in headings also
inherit from the "standard" style, for example).  To find if a style
is a heading, we must traverse this chain (see also L.1.8.9 Style Inheritance in ECMA-376) .

In this commit, I've also removed the comment about figuring out if languages use the same builtins. It appears Dutch Word versions also use the English names like "heading 2" as builtin. Strangely, its parent style is called "Standaard", which is Dutch again.

2020-05-05 15:15 UTC, Vitaliy-1 commented
OOXML is much a mystery to me :) I definitely need to read the standards. Thanks, I'll take a look.

2020-08-27 15:13 UTC, Vitaliy-1 requested changes
Thanks again! This certainly makes sense. Can you make a small change in the comment below? LibreOffice uses capitalizes style  names, to match built-in styles it should be converted to the lower case first.

2020-08-27 15:13 UTC, Vitaliy-1 commented on src/docx2jats/objectModel/Document.php
> +				if (in_array($styleName, $builtinStyles)) return $styleName;
Sorry for such a long delay. Can you also convert $styleName in lower case before comparing with a built-in styles? e.g.: 
```
if (in_array(strtolower($styleName), $builtinStyles)) {
```

2020-08-27 15:32 UTC, sjamaan commented
I can't promise anything; I was using this code for a client and we've decided to switch to a different implementation in the meantime. If I find the time I can take a look.

2020-09-01 16:08 UTC, Vitaliy-1 commented
Not a problem, I'll apply necessary changes.

2020-09-01 16:09 UTC, merged